#Author: Jakub Wlodek

TOP=../..
include $(TOP)/configure/CONFIG

#add macros here

#optimization of db files using dbst(DEFAULT:NO)
#DB_OPT=YES

DB+=NDBar.template
DB+=NDBar_settings.req

include $(TOP)/configure/RULES

#add rules here
